# Back-End production stack of API and DB
# docker-compose up

version: '3.2'

services:
  express: # Back-end REST API
    container_name: production-api
    image: mcflip/oils-backend # my private repo
    ports:
      - "3000:3000" 
    volumes:
      - type: volume  # morgan log files
        source: logvol
        target: /var/log
      - type: volume  # TLS certs
        source: tlsvol
        target: /etc/letsencrypt/
    env_file: .env
    environment:
      - NODE_ENV=production
    links:
      - "database" 
    depends_on:
      - "database"
    restart: always
    command: ["node", "/usr/src/app/server.js"]

  database: # mongo
    container_name: mongo-db
    image: mongo:4.2-bionic
    ports:
      - "27017:27017" 
    restart: unless-stopped # in case you stop the db to do full backup
    volumes:
      - type: volume
        source: dbvol
        target: /data/db
      - './tar:/dump' # mongodump backups
    command: ["mongod", "--bind_ip", "localhost,database", "--auth"]
volumes:
  dbvol:
  logvol:
  tlsvol: 
    driver: local
    driver_opts:
      type: none
      device: /etc/letsencrypt/
      o: bind
