# build environment
FROM node:14 as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
ENV BUILD_TARGET server
ENV NODE_ENV production
COPY package.json package-lock.json /app/
RUN npm ci
COPY . /app
RUN npm run build

FROM node:14-alpine
WORKDIR /usr/src/app
COPY --from=build /app/node_modules /usr/src/app/node_modules/
COPY --from=build /app/.build /usr/src/app/
EXPOSE 3000
CMD ["node", "server.js"]