# build environment
FROM node:12 as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json package-lock.json /app/
RUN npm ci
COPY . /app
RUN npm run build

FROM node:12-alpine
WORKDIR /usr/src/app
COPY --from=build /app/node_modules /usr/src/app/node_modules/
COPY --from=build /app/.build /usr/src/app/
EXPOSE 3000
CMD ["node", "server.js"]