# build environment
FROM node:12-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json /app/package.json
RUN npm install
COPY . /app
RUN npm run build

FROM node:12-alpine
WORKDIR /usr/src/app
COPY wait-for-it.sh /usr/src/app/
COPY --from=build /app/node_modules /usr/src/app/node_modules/
COPY --from=build /app/.build /usr/src/app/
EXPOSE 3000
CMD ["sh", "/usr/src/app/wait-for-it.sh", "database:27017", "--", "node", "server.js"]