# build environment
FROM node:14 as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
ARG DOMAIN
ARG ROOT_URL
ARG IMG_HOST
COPY package.json package-lock.json /app/
RUN npm ci
COPY . /app
RUN npm run build

FROM nginx:1.19.2-alpine
COPY --from=build /app/dist /usr/share/nginx/html
WORKDIR /etc/nginx/conf.d
RUN rm default.conf
COPY nginx/nginx.conf.template .
EXPOSE 443
CMD ["/bin/sh", "-c", "envsubst '${DOMAIN}' < nginx.conf.template > nginx.conf && exec nginx -g 'daemon off;'"]